# Generated by Django 3.2.9 on 2021-11-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('song', models.FileField(null=True, upload_to='')),
                ('album', models.ImageField(null=True, upload_to='album/')),
                ('release', models.DateField(default='12-11-2021')),
                ('image', models.ImageField(null=True, upload_to='cover/')),
                ('like', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
            ],
        ),
    ]
